### PR TITLE
switch to github actions

### LINKED ISSUE #33: Change to new workflow
same as tfs:

- [x] remove pytest from setup.py
- [x] use github actions (all Secrets should already be there), add PR requirements
- [ ] remove travis.yml and travis PR requirements
- [x] clean setup.cfg (imho also addopts should go to teh pytest call directly)
- [x] (version and) descriptions in `__init__.py` 
- [x]  use descriptions and version in `doc/conf.py`,  `setup.py`
- [x] remove bumpversion.cfg
- [x] doc-Makefile: replace `/media/jdilly/Storage/Repositories/` with `/home/jdilly/Software/Documentation/` (thx)
- [x] mark tests as basic (or extended)

### PR DESCRIPTION
**Pull request by mihofer**
Fix #33

### CODE REVIEW

**Review by fsoubelet — CHANGES_REQUESTED** [review]
Few things:

- The `setup.py` should include a `python_requires=">=3.6",` field in the `setup()` function (this is `3.6+`, yeah?)
- Are we sure we want to ditch `setup.cfg`? Where do the `pytest` addopts go?
- Have you checked that the documentation builds properly?
- Remove `.travis.yml`, we have not checked yet that the PR behaves properly only with GA
- @JoschD can you remove the requirement on travis builds statuses for PRs?
- We should also update the build badge on the main `README`. The proper line will be:
`[Cron Testing](https://github.com/pylhc/generic_parser/actions?query=workflow%3A%22Cron+Testing%22)`

**Comment by mihofer** [comment]
> 
> 
> Few things:
> 
>     * The `setup.py` should include a `python_requires=">=3.6",` field in the `setup()` function (this is `3.6+`, yeah?)
> 
>     * Are we sure we want to ditch `setup.cfg`? Where do the `pytest` addopts go?
> 
>     * Have you checked that the documentation builds properly?
> 
>     * Remove `.travis.yml`, we have not checked yet that the PR behaves properly only with GA
> 
>     * @JoschD can you remove the requirement on travis builds statuses for PRs?

- setup.py now includes python requirements
- pytest opt went to the coverage.yml, other stuff is apparently not needed right now
- docu not checked, will have a look right away
- `travis.yml` removal and PR requirements should probably wait until PR #32 is in, also bc the history of this branch is a bit dirty (sry, my bad)

**Comment by fsoubelet** [comment]
> travis.yml removal and PR requirements should probably wait until PR #32 is in

**Comment by fsoubelet** [comment]
Checkpoint: Travis CI builds are gone, PR requirements have been changed to the GA builds. This PR should be good for a merge now.

Envisionned steps are:
1. Merge this
2. Clone and install from master, then check with this code that `omc3` tests are good
3. Make the release
4. See the CI builds in https://github.com/pylhc/omc3/pull/230 get fixed :D

**Review by JoschD — APPROVED** [review]

**Review by fsoubelet — APPROVED** [review]

**Pull request merged**
